var numberOfTotalStudents = 45;
var numberOfPresentStudent = 30;
var numberOfAbesentStudent = numberOfTotalStudents - numberOfPresentStudent;
console.log(numberOfAbesentStudent);
var englishTotalMarks = 100;
var englishObtainMarks = 75;
var urduTotalMarks = 100;
var urduObtainMarks = 67.5;
var mathsTotalMarks = 100;
var mathsObtainMarks = 85;
var scienceTotalMarks = 100;
var scienceObtainMarks = 85.5;
var socialStudiesTotalMarks = 50;
var socialStudiesObtainMarks = 45;
var computerTotalMarks = 50;
var computerObtainMarks = 45.5;
var islamiatTotalMarks = 50;
var islamiatObtainMarks = 49.5;
var totalMarks = 550;
var totalObtainMarks = englishObtainMarks + urduObtainMarks + mathsObtainMarks + scienceObtainMarks + socialStudiesObtainMarks + computerObtainMarks + islamiatObtainMarks;
console.log(totalObtainMarks);
var result = totalObtainMarks / totalMarks * 100;
console.log(result);
