let numberOfTotalStudents = 45;
let numberOfPresentStudent = 30;
let numberOfAbesentStudent =  numberOfTotalStudents - numberOfPresentStudent ;
console.log(numberOfAbesentStudent);
let englishTotalMarks = 100;
let englishObtainMarks = 75;
let urduTotalMarks = 100;
let urduObtainMarks = 67.5;
let mathsTotalMarks = 100;
let mathsObtainMarks = 85;
let scienceTotalMarks = 100;
let scienceObtainMarks = 85.5;
let socialStudiesTotalMarks = 50;
let socialStudiesObtainMarks = 45;
let computerTotalMarks = 50;
let computerObtainMarks = 45.5;
let islamiatTotalMarks = 50;
let islamiatObtainMarks = 49.5;
let totalMarks = 550;
let totalObtainMarks = englishObtainMarks + urduObtainMarks + mathsObtainMarks + scienceObtainMarks + socialStudiesObtainMarks + computerObtainMarks + islamiatObtainMarks;
console.log(totalObtainMarks);
let result = totalObtainMarks / totalMarks * 100;
console.log(result);
